use itertools::Itertools;

use super::domain::{BeadError, BeadTemplate};

pub fn beads_to_jsonl(beads: &[BeadTemplate]) -> Result<String, BeadError> {
  beads
    .iter()
    .map(|bead| serde_json::to_string(bead).map_err(|err| BeadError::JsonError(err.to_string())))
    .collect::<Result<Vec<_>, _>>()
    .map(|lines| lines.join("\n"))
}

pub fn beads_to_enhanced_cue(beads: &[BeadTemplate]) -> Result<String, BeadError> {
  if beads.is_empty() {
    return Ok(String::new());
  }

  let invalid = beads.iter().any(|bead| bead.title.trim().is_empty());
  if invalid {
    return Err(BeadError::EmptyTitle);
  }

  let header = vec![
    "// Enhanced CUE Template for Work Items".to_string(),
    "// Generated by clarity-web intent beads module".to_string(),
    String::new(),
    "package beads".to_string(),
    String::new(),
  ];

  let metadata = vec![
    "// Section 1: Metadata".to_string(),
    "metadata: {".to_string(),
    format!("    total_beads: {}", beads.len()),
    "    format_version: \"1.0\"".to_string(),
    "    generator: \"clarity-web-intent-beads\"".to_string(),
    "}".to_string(),
    String::new(),
  ];

  let profile_types = section_count(
    "Section 2: Profile Types",
    "profile_types",
    &beads
      .iter()
      .map(|bead| bead.profile_type.clone())
      .collect::<Vec<_>>(),
  );
  let issue_types = section_count(
    "Section 3: Issue Types",
    "issue_types",
    &beads
      .iter()
      .map(|bead| bead.issue_type.clone())
      .collect::<Vec<_>>(),
  );
  let priorities = section_priority(beads);
  let labels = section_labels(beads);
  let graph = section_dependencies(beads);
  let records = section_records(beads);

  Ok(
    [
      header,
      metadata,
      profile_types,
      issue_types,
      priorities,
      labels,
      graph,
      records,
    ]
    .into_iter()
    .flatten()
    .join("\n"),
  )
}

fn section_count(section: &str, key: &str, values: &[String]) -> Vec<String> {
  let lines = values
    .iter()
    .counts()
    .into_iter()
    .map(|(name, count)| format!("    {name}: {count}"));
  std::iter::once(format!("// {section}"))
    .chain(std::iter::once(format!("{key}: {{")))
    .chain(lines)
    .chain(std::iter::once("}".to_string()))
    .chain(std::iter::once(String::new()))
    .collect()
}

fn section_priority(beads: &[BeadTemplate]) -> Vec<String> {
  let lines = (1_u8..=5_u8).map(|priority| {
    let count = beads
      .iter()
      .filter(|bead| bead.priority == priority)
      .count();
    format!("    p{priority}: {count}")
  });
  std::iter::once("// Section 4: Priority Distribution".to_string())
    .chain(std::iter::once("priority_distribution: {".to_string()))
    .chain(lines)
    .chain(std::iter::once("}".to_string()))
    .chain(std::iter::once(String::new()))
    .collect()
}

fn section_labels(beads: &[BeadTemplate]) -> Vec<String> {
  let labels = beads
    .iter()
    .flat_map(|bead| bead.labels.iter())
    .cloned()
    .unique()
    .map(|label| format!("    \"{label}\": true"));
  std::iter::once("// Section 5: Labels Index".to_string())
    .chain(std::iter::once("labels_index: {".to_string()))
    .chain(labels)
    .chain(std::iter::once("}".to_string()))
    .chain(std::iter::once(String::new()))
    .collect()
}

fn section_dependencies(beads: &[BeadTemplate]) -> Vec<String> {
  let items = beads
    .iter()
    .filter(|bead| !bead.dependencies.is_empty())
    .flat_map(|bead| {
      std::iter::once(format!("    \"{}\": [", escape_cue_string(&bead.title)))
        .chain(
          bead
            .dependencies
            .iter()
            .map(|dep| format!("        \"{}\",", escape_cue_string(dep))),
        )
        .chain(std::iter::once("    ]".to_string()))
    });
  std::iter::once("// Section 6: Dependencies Graph".to_string())
    .chain(std::iter::once("dependencies_graph: {".to_string()))
    .chain(items)
    .chain(std::iter::once("}".to_string()))
    .chain(std::iter::once(String::new()))
    .collect()
}

fn section_records(beads: &[BeadTemplate]) -> Vec<String> {
  let records = beads.iter().enumerate().flat_map(|(index, bead)| {
    let id = index + 1;
    std::iter::once("    {".to_string())
      .chain(std::iter::once(format!(
        "        // Section 7: Record {id}"
      )))
      .chain(std::iter::once(format!("        id: \"bead-{id}\"")))
      .chain(std::iter::once(format!(
        "        title: \"{}\"",
        escape_cue_string(&bead.title)
      )))
      .chain(std::iter::once(format!(
        "        description: \"{}\"",
        escape_cue_string(&bead.description)
      )))
      .chain(std::iter::once(
        "        // Section 8: Classification".to_string(),
      ))
      .chain(std::iter::once(format!(
        "        profile_type: \"{}\"",
        bead.profile_type
      )))
      .chain(std::iter::once(format!(
        "        issue_type: \"{}\"",
        bead.issue_type
      )))
      .chain(std::iter::once(format!(
        "        priority: {}",
        bead.priority
      )))
      .chain(std::iter::once(
        "        // Section 16: Verification Status".to_string(),
      ))
      .chain(std::iter::once(
        "        verification_status: \"pending\"".to_string(),
      ))
      .chain(std::iter::once("    }".to_string()))
  });
  std::iter::once("// Sections 7-16: Bead Records".to_string())
    .chain(std::iter::once("beads: [".to_string()))
    .chain(records)
    .chain(std::iter::once("]".to_string()))
    .collect()
}

fn escape_cue_string(value: &str) -> String {
  value
    .replace('\\', "\\\\")
    .replace('"', "\\\"")
    .replace('\n', "\\n")
    .replace('\r', "\\r")
    .replace('\t', "\\t")
}
