use itertools::Itertools;

use super::domain::{BeadError, BeadTemplate};

/// Decodes a JSON array of beads into `Vec<BeadTemplate>`.
///
/// # Errors
/// Returns `BeadError::JsonError` if the input is not valid JSON or
/// does not conform to the expected bead array structure.
pub fn decode_beads_json(json: &str) -> Result<Vec<BeadTemplate>, BeadError> {
  serde_json::from_str(json).map_err(|err| BeadError::JsonError(err.to_string()))
}

/// Renders bead templates as JSONL.
///
/// # Errors
/// Returns `BeadError::JsonError` if any bead fails to serialize.
pub fn beads_to_jsonl(beads: &[BeadTemplate]) -> Result<String, BeadError> {
  beads
    .iter()
    .map(|bead| serde_json::to_string(bead).map_err(|err| BeadError::JsonError(err.to_string())))
    .collect::<Result<Vec<_>, _>>()
    .map(|lines| lines.join("\n"))
}

/// Renders bead templates as an enhanced CUE document.
///
/// # Errors
/// Returns `BeadError::EmptyTitle` when any bead has an empty title.
pub fn beads_to_enhanced_cue(beads: &[BeadTemplate]) -> Result<String, BeadError> {
  if beads.is_empty() {
    return Ok(String::new());
  }

  let invalid = beads.iter().any(|bead| bead.title.trim().is_empty());
  if invalid {
    return Err(BeadError::EmptyTitle);
  }

  let header = vec![
    "// Enhanced CUE Template for Work Items".to_string(),
    "// Generated by clarity-web intent beads module".to_string(),
    String::new(),
    "package beads".to_string(),
    String::new(),
  ];

  let metadata = vec![
    "// Section 1: Metadata".to_string(),
    "metadata: {".to_string(),
    format!("    total_beads: {}", beads.len()),
    "    format_version: \"1.0\"".to_string(),
    "    generator: \"clarity-web-intent-beads\"".to_string(),
    "}".to_string(),
    String::new(),
  ];

  let profile_types = section_count(
    "Section 2: Profile Types",
    "profile_types",
    &beads
      .iter()
      .map(|bead| bead.profile_type.clone())
      .collect::<Vec<_>>(),
  );
  let issue_types = section_count(
    "Section 3: Issue Types",
    "issue_types",
    &beads
      .iter()
      .map(|bead| bead.issue_type.clone())
      .collect::<Vec<_>>(),
  );
  let priorities = section_priority(beads);
  let labels = section_labels(beads);
  let graph = section_dependencies(beads);
  let records = section_records(beads);

  Ok(
    [
      header,
      metadata,
      profile_types,
      issue_types,
      priorities,
      labels,
      graph,
      records,
    ]
    .into_iter()
    .flatten()
    .join("\n"),
  )
}

fn section_count(section: &str, key: &str, values: &[String]) -> Vec<String> {
  let lines = values
    .iter()
    .counts()
    .into_iter()
    .map(|(name, count)| format!("    {name}: {count}"));
  std::iter::once(format!("// {section}"))
    .chain(std::iter::once(format!("{key}: {{")))
    .chain(lines)
    .chain(std::iter::once("}".to_string()))
    .chain(std::iter::once(String::new()))
    .collect()
}

fn section_priority(beads: &[BeadTemplate]) -> Vec<String> {
  let lines = (1_u8..=5_u8).map(|priority| {
    let count = beads
      .iter()
      .filter(|bead| bead.priority == priority)
      .count();
    format!("    p{priority}: {count}")
  });
  std::iter::once("// Section 4: Priority Distribution".to_string())
    .chain(std::iter::once("priority_distribution: {".to_string()))
    .chain(lines)
    .chain(std::iter::once("}".to_string()))
    .chain(std::iter::once(String::new()))
    .collect()
}

fn section_labels(beads: &[BeadTemplate]) -> Vec<String> {
  let labels = beads
    .iter()
    .flat_map(|bead| bead.labels.iter())
    .cloned()
    .unique()
    .map(|label| format!("    \"{label}\": true"));
  std::iter::once("// Section 5: Labels Index".to_string())
    .chain(std::iter::once("labels_index: {".to_string()))
    .chain(labels)
    .chain(std::iter::once("}".to_string()))
    .chain(std::iter::once(String::new()))
    .collect()
}

fn section_dependencies(beads: &[BeadTemplate]) -> Vec<String> {
  let items = beads
    .iter()
    .filter(|bead| !bead.dependencies.is_empty())
    .flat_map(|bead| {
      std::iter::once(format!("    \"{}\": [", escape_cue_string(&bead.title)))
        .chain(
          bead
            .dependencies
            .iter()
            .map(|dep| format!("        \"{}\",", escape_cue_string(dep))),
        )
        .chain(std::iter::once("    ]".to_string()))
    });
  std::iter::once("// Section 6: Dependencies Graph".to_string())
    .chain(std::iter::once("dependencies_graph: {".to_string()))
    .chain(items)
    .chain(std::iter::once("}".to_string()))
    .chain(std::iter::once(String::new()))
    .collect()
}

fn section_records(beads: &[BeadTemplate]) -> Vec<String> {
  let records = beads.iter().enumerate().flat_map(|(index, bead)| {
    let id = index + 1;
    std::iter::once("    {".to_string())
      .chain(std::iter::once(format!(
        "        // Section 7: Record {id}"
      )))
      .chain(std::iter::once(format!("        id: \"bead-{id}\"")))
      .chain(std::iter::once(format!(
        "        title: \"{}\"",
        escape_cue_string(&bead.title)
      )))
      .chain(std::iter::once(format!(
        "        description: \"{}\"",
        escape_cue_string(&bead.description)
      )))
      .chain(std::iter::once(
        "        // Section 8: Classification".to_string(),
      ))
      .chain(std::iter::once(format!(
        "        profile_type: \"{}\"",
        bead.profile_type
      )))
      .chain(std::iter::once(format!(
        "        issue_type: \"{}\"",
        bead.issue_type
      )))
      .chain(std::iter::once(format!(
        "        priority: {}",
        bead.priority
      )))
      .chain(std::iter::once(
        "        // Section 16: Verification Status".to_string(),
      ))
      .chain(std::iter::once(
        "        verification_status: \"pending\"".to_string(),
      ))
      .chain(std::iter::once("    }".to_string()))
  });
  std::iter::once("// Sections 7-16: Bead Records".to_string())
    .chain(std::iter::once("beads: [".to_string()))
    .chain(records)
    .chain(std::iter::once("]".to_string()))
    .collect()
}

fn escape_cue_string(value: &str) -> String {
  value
    .replace('\\', "\\\\")
    .replace('"', "\\\"")
    .replace('\n', "\\n")
    .replace('\r', "\\r")
    .replace('\t', "\\t")
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::float_cmp, clippy::needless_collect, clippy::unnecessary_debug_formatting, clippy::match_same_arms, clippy::option_if_let_else, clippy::suspicious_else_formatting, clippy::manual_let_else, clippy::match_wild_err_arm, clippy::match_like_matches_macro, clippy::needless_pass_by_value)]
mod tests {
  use super::*;

  #[test]
  fn test_decode_beads_json_empty_array() {
    let result = decode_beads_json("[]");
    assert!(result.is_ok());
    let beads = result.expect("checked above");
    assert!(beads.is_empty());
  }

  #[test]
  fn test_decode_beads_json_single_bead() {
    let json = r#"[{
      "title": "Test Bead",
      "description": "Test description",
      "profile_type": "feature",
      "priority": 3,
      "issue_type": "task",
      "labels": ["test"],
      "ai_hints": "Some hints",
      "acceptance_criteria": ["criterion 1"],
      "dependencies": []
    }]"#;
    let result = decode_beads_json(json);
    assert!(result.is_ok());
    let beads = result.expect("checked above");
    assert_eq!(beads.len(), 1);
    assert_eq!(beads[0].title, "Test Bead");
    assert_eq!(beads[0].description, "Test description");
    assert_eq!(beads[0].profile_type, "feature");
    assert_eq!(beads[0].priority, 3);
  }

  #[test]
  fn test_decode_beads_json_multiple_beads() {
    let json = r#"[
      {"title": "First", "description": "Desc 1", "profile_type": "p1", "priority": 1, "issue_type": "bug", "labels": [], "ai_hints": "", "acceptance_criteria": [], "dependencies": []},
      {"title": "Second", "description": "Desc 2", "profile_type": "p2", "priority": 2, "issue_type": "feature", "labels": [], "ai_hints": "", "acceptance_criteria": [], "dependencies": []}
    ]"#;
    let result = decode_beads_json(json);
    assert!(result.is_ok());
    let beads = result.expect("checked above");
    assert_eq!(beads.len(), 2);
    assert_eq!(beads[0].title, "First");
    assert_eq!(beads[1].title, "Second");
  }

  #[test]
  fn test_decode_beads_json_invalid_json() {
    let result = decode_beads_json("not valid json");
    assert!(result.is_err());
    if let Err(BeadError::JsonError(msg)) = result {
      assert!(msg.contains("expected"));
    } else {
      panic!("Expected JsonError");
    }
  }

  #[test]
  fn test_roundtrip_jsonl() {
    let original = vec![BeadTemplate {
      title: "Test".to_string(),
      description: "Description".to_string(),
      profile_type: "profile".to_string(),
      priority: 2,
      issue_type: "feature".to_string(),
      labels: vec!["label1".to_string()],
      ai_hints: "hints".to_string(),
      acceptance_criteria: vec!["criterion".to_string()],
      dependencies: vec![],
    }];

    let jsonl = beads_to_jsonl(&original).expect("serialization should succeed");
    let json_array = format!("[{}]", jsonl.replace('\n', ","));
    let decoded = decode_beads_json(&json_array).expect("deserialization should succeed");

    assert_eq!(decoded.len(), original.len());
    assert_eq!(decoded[0].title, original[0].title);
    assert_eq!(decoded[0].description, original[0].description);
  }

  #[test]
  fn test_public_api_via_intent_module() {
    // This test demonstrates public usage via the re-exported API
    use crate::intent::decode_beads_json;

    let json = r#"[{
      "title": "API Test",
      "description": "Public API test",
      "profile_type": "test",
      "priority": 1,
      "issue_type": "task",
      "labels": [],
      "ai_hints": "",
      "acceptance_criteria": [],
      "dependencies": []
    }]"#;

    let result = decode_beads_json(json);
    assert!(result.is_ok());
    let beads = result.expect("checked above");
    assert_eq!(beads[0].title, "API Test");
  }
}
