pub(super) const STATE_CHANGE_KEYWORDS: &[&str] = &[
  "create", "update", "delete", "remove", "modify", "insert", "save", "write", "destroy",
  "archive", "restore", "purge", "reset", "clear", "set", "assign", "transfer", "move", "copy",
  "clone", "merge",
];

pub(super) const NOTIFICATION_KEYWORDS: &[&str] = &[
  "email",
  "notify",
  "send",
  "alert",
  "webhook",
  "callback",
  "broadcast",
  "publish",
  "emit",
  "push",
  "sms",
  "message",
  "mail",
  "notification",
  "subscribe",
  "dispatch",
  "trigger",
  "announce",
  "signal",
];

pub(super) const CASCADE_KEYWORDS: &[&str] = &[
  "cascade",
  "propagate",
  "affect",
  "related",
  "dependent",
  "linked",
  "associated",
  "connected",
  "chain",
  "ripple",
  "downstream",
  "upstream",
  "sync",
  "synchronize",
  "replicate",
  "mirror",
];

pub(super) const RACE_CONDITION_KEYWORDS: &[&str] = &[
  "concurrent",
  "parallel",
  "simultaneous",
  "atomic",
  "lock",
  "mutex",
  "race",
  "thread",
  "async",
  "await",
  "conflict",
  "exclusive",
  "shared",
  "synchronize",
  "volatile",
  "interleave",
];

pub(super) const ROLLBACK_KEYWORDS: &[&str] = &[
  "transaction",
  "rollback",
  "revert",
  "undo",
  "compensate",
  "recover",
  "restore",
  "backup",
  "snapshot",
  "version",
  "history",
  "audit",
  "reversible",
  "idempotent",
  "replay",
];

pub(super) const HIGH_SEVERITY_KEYWORDS: &[&str] = &[
  "critical",
  "severe",
  "urgent",
  "important",
  "essential",
  "vital",
  "irreversible",
  "permanent",
  "destructive",
  "dangerous",
  "sensitive",
  "secure",
  "encrypt",
  "auth",
  "permission",
  "admin",
  "root",
];

pub(super) const CRITICAL_SEVERITY_KEYWORDS: &[&str] = &[
  "emergency",
  "fatal",
  "catastrophic",
  "unrecoverable",
  "corrupt",
  "breach",
  "expose",
  "leak",
  "compromise",
  "invalidate",
  "destroy",
  "wipe",
  "eliminate",
  "terminate",
  "abort",
];
